# Generated by Django 3.1.1 on 2022-03-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='order_id',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='razorpay_payment_id',
        ),
    ]
