# Generated by Django 3.1.1 on 2022-03-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220308_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
